import puppeteer from 'puppeteer';
import path from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';
import AppError from '../utils/appError.js';
import User from '../models/User.js';
import Asset from '../models/Asset.js';
import Liability from '../models/Liability.js';
import Transaction from '../models/Transaction.js';
import Investment from '../models/Investment.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Helper function to check if user has access to a category
const hasAccess = (user, category) => {
  if (!user.permissions) return true;
  return user.permissions[category] !== false;
};

// Generate PDF report
export const generateReport = async (req, res, next) => {
  try {
    const { type = 'overview', startDate, endDate } = req.query;
    const userId = req.user._id;
    
    // Get the user data
    const user = await User.findById(userId);
    const currentDate = new Date().toLocaleDateString();
    
    // Generate a simple HTML report
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Financial Report</title>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; margin: 0; padding: 20px; }
          h1, h2 { color: #2c3e50; }
          .header { text-align: center; margin-bottom: 30px; }
          .section { margin-bottom: 30px; }
          .logo { font-size: 24px; font-weight: bold; color: #3498db; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">FinanceAI</div>
          <h1>Financial Report</h1>
          <p>Generated on: ${currentDate}</p>
          <p>For: ${user.name}</p>
        </div>
        
        <div class="section">
          <h2>Report Summary</h2>
          <p>This is a comprehensive financial report generated by FinanceAI.</p>
          <p>Report Type: ${type}</p>
          <p>This report contains your financial overview and insights.</p>
        </div>
        
        <div class="footer" style="margin-top: 40px; text-align: center; color: #666; font-size: 0.9em;">
          <p>Generated by FinanceAI - Your Personal Finance Assistant</p>
          <p>This is an automatically generated report. For official statements, please consult with a financial advisor.</p>
        </div>
      </body>
      </html>
    `;
    
    // Generate PDF
    const browser = await puppeteer.launch({
      headless: 'new',
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });
    
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    
    // Generate PDF
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20mm',
        right: '20mm',
        bottom: '20mm',
        left: '20mm',
      },
    });
    
    await browser.close();
    
    // Set response headers
    res.set({
      'Content-Type': 'application/pdf',
      'Content-Disposition': 'attachment; filename=financial-report.pdf',
      'Content-Length': pdfBuffer.length,
    });
    
    // Send the PDF
    res.send(pdfBuffer);
    
  } catch (err) {
    console.error('Error generating report:', err);
    next(new AppError('Error generating report', 500));
  }
};

// Generate a financial statement
export const generateFinancialStatement = async (req, res, next) => {
  try {
    const { type = 'balance-sheet' } = req.query;
    const userId = req.user._id;
    
    // Get financial data
    const [assets, liabilities, transactions] = await Promise.all([
      Asset.find({ user: userId }),
      Liability.find({ user: userId }),
      Transaction.find({ user: userId })
        .sort('-date')
        .limit(100),
    ]);
    
    // Calculate totals
    const totalAssets = assets.reduce((sum, asset) => sum + (asset.currentValue || 0), 0);
    const totalLiabilities = liabilities.reduce((sum, liability) => sum + (liability.currentBalance || 0), 0);
    const netWorth = totalAssets - totalLiabilities;
    
    // Generate HTML for the statement
    let html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Financial Statement</title>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; margin: 0; padding: 20px; }
          h1, h2 { color: #2c3e50; }
          .header { text-align: center; margin-bottom: 30px; }
          .section { margin-bottom: 30px; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
          th { background-color: #f2f2f2; }
          .total { font-weight: bold; }
          .positive { color: green; }
          .negative { color: red; }
          .logo { font-size: 24px; font-weight: bold; color: #3498db; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">FinanceAI</div>
          <h1>Financial Statement</h1>
          <p>Generated on: ${new Date().toLocaleDateString()}</p>
        </div>
        
        <div class="section">
          <h2>Net Worth</h2>
          <table>
            <tr>
              <td>Total Assets</td>
              <td>$${totalAssets.toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
            </tr>
            <tr>
              <td>Total Liabilities</td>
              <td>$${totalLiabilities.toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
            </tr>
            <tr class="total">
              <td>Net Worth</td>
              <td class="${netWorth >= 0 ? 'positive' : 'negative'}">
                $${netWorth.toLocaleString(undefined, { minimumFractionDigits: 2 })}
              </td>
            </tr>
          </table>
        </div>
        
        <div class="section">
          <h2>Assets</h2>
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Current Value</th>
              </tr>
            </thead>
            <tbody>
              ${assets.map(asset => `
                <tr>
                  <td>${asset.name}</td>
                  <td>${asset.type}</td>
                  <td>$${(asset.currentValue || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
                </tr>
              `).join('')}
            </tbody>
            <tfoot>
              <tr class="total">
                <td colspan="2">Total Assets</td>
                <td>$${totalAssets.toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
              </tr>
            </tfoot>
          </table>
        </div>
        
        <div class="section">
          <h2>Liabilities</h2>
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Current Balance</th>
                <th>Interest Rate</th>
              </tr>
            </thead>
            <tbody>
              ${liabilities.map(liability => `
                <tr>
                  <td>${liability.name}</td>
                  <td>${liability.type}</td>
                  <td>$${(liability.currentBalance || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
                  <td>${(liability.interestRate || 0).toFixed(2)}%</td>
                </tr>
              `).join('')}
            </tbody>
            <tfoot>
              <tr class="total">
                <td colspan="2">Total Liabilities</td>
                <td>$${totalLiabilities.toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
                <td></td>
              </tr>
            </tfoot>
          </table>
        </div>
        
        <div class="section">
          <h2>Recent Transactions</h2>
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Description</th>
                <th>Amount</th>
                <th>Category</th>
              </tr>
            </thead>
            <tbody>
              ${transactions.map(tx => `
                <tr>
                  <td>${new Date(tx.date).toLocaleDateString()}</td>
                  <td>${tx.description}</td>
                  <td class="${tx.amount >= 0 ? 'positive' : 'negative'}">
                    $${Math.abs(tx.amount).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                  </td>
                  <td>${tx.category}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>
        
        <div class="footer" style="margin-top: 40px; text-align: center; color: #666; font-size: 0.9em;">
          <p>Generated by FinanceAI - Your Personal Finance Assistant</p>
          <p>This is an automatically generated report. For official statements, please consult with a financial advisor.</p>
        </div>
      </body>
      </html>
    `;
    
    // Generate PDF
    const browser = await puppeteer.launch({
      headless: 'new',
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });
    
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    
    // Generate PDF
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20mm',
        right: '20mm',
        bottom: '20mm',
        left: '20mm',
      },
    });
    
    await browser.close();
    
    // Set response headers
    res.set({
      'Content-Type': 'application/pdf',
      'Content-Disposition': 'attachment; filename=financial-statement.pdf',
      'Content-Length': pdfBuffer.length,
    });
    
    // Send the PDF
    res.send(pdfBuffer);
    
  } catch (err) {
    console.error('Error generating financial statement:', err);
    next(new AppError('Error generating financial statement', 500));
  }
};

// Export data in various formats
export const exportData = async (req, res, next) => {
  try {
    const { format = 'json', type = 'transactions' } = req.query;
    const userId = req.user._id;
    
    // Get data based on type
    let data;
    switch (type) {
      case 'transactions':
        data = await Transaction.find({ user: userId });
        break;
      case 'assets':
        data = await Asset.find({ user: userId });
        break;
      case 'liabilities':
        data = await Liability.find({ user: userId });
        break;
      case 'investments':
        data = await Investment.find({ user: userId });
        break;
      default:
        return next(new AppError('Invalid data type', 400));
    }
    
    // Convert data to requested format
    let result;
    let contentType;
    let extension;
    
    switch (format.toLowerCase()) {
      case 'json':
        result = JSON.stringify(data, null, 2);
        contentType = 'application/json';
        extension = 'json';
        break;
        
      case 'csv':
        // Convert array of objects to CSV
        if (data.length === 0) {
          result = '';
        } else {
          // Get headers from first object
          const headers = Object.keys(data[0].toObject ? data[0].toObject() : data[0]);
          
          // Create CSV rows
          const rows = data.map(item => {
            const obj = item.toObject ? item.toObject() : item;
            return headers.map(header => {
              let value = obj[header];
              // Handle nested objects and arrays
              if (value && typeof value === 'object') {
                if (Array.isArray(value)) {
                  value = value.join('; ');
                } else if (value._id) {
                  value = value._id;
                } else {
                  value = JSON.stringify(value);
                }
              }
              // Escape quotes and wrap in quotes if contains comma or newline
              if (typeof value === 'string' && (value.includes(',') || value.includes('\n'))) {
                value = `"${value.replace(/"/g, '""')}"`;
              }
              return value || '';
            });
          });
          
          // Combine headers and rows
          const csvRows = [
            headers.join(','),
            ...rows.map(row => row.join(','))
          ];
          
          result = csvRows.join('\n');
        }
        contentType = 'text/csv';
        extension = 'csv';
        break;
        
      default:
        return next(new AppError('Unsupported export format', 400));
    }
    
    // Set response headers
    res.set({
      'Content-Type': contentType,
      'Content-Disposition': `attachment; filename=${type}-export.${extension}`,
      'Content-Length': Buffer.byteLength(result, 'utf8'),
    });
    
    // Send the data
    res.send(result);
    
  } catch (err) {
    console.error('Error exporting data:', err);
    next(new AppError('Error exporting data', 500));
  }
};
